version: '3.0'

services:
  app:
    build: .
    container_name: bot_app
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      HOST: "db"
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_PASS: "${DB_PASS}"
    depends_on:
      - db
  db:
    image: postgres
    container_name: bot_postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    ports:
      - '5432:5432'