version: '3.0'

services:
    db:
      image: postgres
      container_name: bot_postgres
      environment:
        POSTGRES_USER: "${DB_USER}"
        POSTGRES_DB: "${DB_NAME}"
        POSTGRES_PASSWORD: "${DB_PASS}"
      ports:
        - '5432:5432'